// Default wording of every editable site text. The back-office (Textes du site)
// overrides these; keep in sync with database/seeders/SiteTextSeeder.php.
export type SiteTextType = "text" | "textarea" | "lines" | "pairs";

export type SiteTextDef = {
  key: string;
  group: string;
  label: string;
  type: SiteTextType;
  fields: string[] | null;
  value: string;
};

export const SITE_TEXT_DEFS: SiteTextDef[] = [
  { key: "menu.home", group: "Menu", label: "Accueil", type: "text", fields: null, value: "Accueil" },
  { key: "menu.services", group: "Menu", label: "Services", type: "text", fields: null, value: "Services" },
  { key: "menu.services_all", group: "Menu", label: "Lien « Tous les services »", type: "text", fields: null, value: "Tous les services" },
  { key: "menu.projects", group: "Menu", label: "Réalisations", type: "text", fields: null, value: "Réalisations" },
  { key: "menu.products", group: "Menu", label: "Produits", type: "text", fields: null, value: "Produits" },
  { key: "menu.about", group: "Menu", label: "À propos (menu)", type: "text", fields: null, value: "À propos" },
  { key: "menu.about_company", group: "Menu", label: "Sous-menu « Notre entreprise »", type: "text", fields: null, value: "Notre entreprise" },
  { key: "menu.news", group: "Menu", label: "Sous-menu « Actualités »", type: "text", fields: null, value: "Actualités" },
  { key: "menu.contact", group: "Menu", label: "Contact", type: "text", fields: null, value: "Contact" },
  { key: "menu.quote_cta", group: "Menu", label: "Bouton du menu (devis)", type: "text", fields: null, value: "Devis gratuit" },
  { key: "footer.nav_title", group: "Pied de page", label: "Titre colonne navigation", type: "text", fields: null, value: "Navigation" },
  { key: "footer.services_title", group: "Pied de page", label: "Titre colonne services", type: "text", fields: null, value: "Nos services" },
  { key: "footer.contact_title", group: "Pied de page", label: "Titre colonne contact", type: "text", fields: null, value: "Contact" },
  { key: "footer.tagline", group: "Pied de page", label: "Ligne sous le copyright", type: "text", fields: null, value: "Importation • Marbrerie • Ébénisterie • Menuiserie • Commerce général" },
  { key: "footer.credit_label", group: "Pied de page", label: "Texte avant le nom du développeur", type: "text", fields: null, value: "Développé par" },
  { key: "footer.credit_name", group: "Pied de page", label: "Nom du développeur", type: "text", fields: null, value: "Ted's Service" },
  { key: "footer.credit_url", group: "Pied de page", label: "Lien du développeur", type: "text", fields: null, value: "https://tedsservice.com" },
  { key: "why.eyebrow", group: "Pourquoi nous choisir", label: "Petit titre", type: "text", fields: null, value: "Notre différence" },
  { key: "why.title", group: "Pourquoi nous choisir", label: "Titre", type: "text", fields: null, value: "Pourquoi nous choisir ?" },
  { key: "why.description", group: "Pourquoi nous choisir", label: "Texte d'introduction", type: "textarea", fields: null, value: "Une entreprise multi-services pensée pour simplifier vos projets, de l'idée à la réalisation." },
  { key: "why.items", group: "Pourquoi nous choisir", label: "Les 4 atouts (un par ligne : titre | description)", type: "pairs", fields: ["title", "description"], value: "Savoir-faire artisanal | Des équipes expérimentées dans le travail du marbre, du bois et des matériaux importés.\nRéalisations sur mesure | Chaque projet est pensé et fabriqué selon vos besoins exacts, du croquis à la pose.\nMatériaux sélectionnés | Des matières premières importées et sélectionnées pour leur qualité et leur durabilité.\nAccompagnement complet | Du devis à la livraison, un interlocuteur unique pour suivre votre projet." },
  { key: "cta.title", group: "Appel à l'action", label: "Titre", type: "text", fields: null, value: "Vous avez un projet ?" },
  { key: "cta.text", group: "Appel à l'action", label: "Texte", type: "textarea", fields: null, value: "Parlez-nous de votre projet et recevez un devis personnalisé de notre équipe." },
  { key: "cta.button", group: "Appel à l'action", label: "Bouton", type: "text", fields: null, value: "Demander un devis" },
  { key: "newsletter.title", group: "Newsletter", label: "Titre", type: "text", fields: null, value: "Restez informés de nos actualités" },
  { key: "newsletter.text", group: "Newsletter", label: "Texte", type: "textarea", fields: null, value: "Nouvelles réalisations, nouveaux produits et offres : recevez nos actualités directement par email." },
  { key: "newsletter.button", group: "Newsletter", label: "Bouton", type: "text", fields: null, value: "S'inscrire" },
  { key: "marquee.items", group: "Bandeau défilant", label: "Mots du bandeau (un par ligne)", type: "lines", fields: null, value: "Importation\nMarbrerie\nÉbénisterie\nMenuiserie\nCommerce général" },
  { key: "home.intro_eyebrow", group: "Accueil - sections", label: "Présentation : petit titre", type: "text", fields: null, value: "Qui sommes-nous" },
  { key: "home.intro_title", group: "Accueil - sections", label: "Présentation : titre", type: "text", fields: null, value: "ENGOBO GROUP, un savoir-faire au service de vos projets" },
  { key: "home.intro_text", group: "Accueil - sections", label: "Présentation : second paragraphe", type: "textarea", fields: null, value: "De l'importation de matériaux à la pose finale, nos équipes interviennent à chaque étape pour garantir des réalisations durables, esthétiques et conformes à vos attentes." },
  { key: "home.intro_more", group: "Accueil - sections", label: "Présentation : bouton", type: "text", fields: null, value: "En savoir plus" },
  { key: "home.intro_stat_label", group: "Accueil - sections", label: "Présentation : libellé du chiffre (domaines)", type: "text", fields: null, value: "Domaines d'activité" },
  { key: "home.services_eyebrow", group: "Accueil - sections", label: "Services : petit titre", type: "text", fields: null, value: "Ce que nous faisons" },
  { key: "home.services_title", group: "Accueil - sections", label: "Services : titre", type: "text", fields: null, value: "Nos domaines d'activité" },
  { key: "home.services_text", group: "Accueil - sections", label: "Services : texte", type: "textarea", fields: null, value: "Cinq métiers complémentaires pour accompagner vos projets du sourcing des matériaux à la pose finale." },
  { key: "home.products_eyebrow", group: "Accueil - sections", label: "Produits : petit titre", type: "text", fields: null, value: "Catalogue" },
  { key: "home.products_title", group: "Accueil - sections", label: "Produits : titre", type: "text", fields: null, value: "Nos produits" },
  { key: "home.products_text", group: "Accueil - sections", label: "Produits : texte", type: "textarea", fields: null, value: "Une sélection de matériaux et de mobilier disponibles à la vente ou sur devis." },
  { key: "home.products_button", group: "Accueil - sections", label: "Produits : bouton", type: "text", fields: null, value: "Voir tout le catalogue" },
  { key: "home.projects_eyebrow", group: "Accueil - sections", label: "Réalisations : petit titre", type: "text", fields: null, value: "Portfolio" },
  { key: "home.projects_title", group: "Accueil - sections", label: "Réalisations : titre", type: "text", fields: null, value: "Nos réalisations" },
  { key: "home.projects_text", group: "Accueil - sections", label: "Réalisations : texte", type: "textarea", fields: null, value: "Un aperçu de nos chantiers récents en marbrerie, menuiserie, ébénisterie et commerce général." },
  { key: "home.projects_button", group: "Accueil - sections", label: "Réalisations : bouton", type: "text", fields: null, value: "Voir toutes les réalisations" },
  { key: "home.testimonials_eyebrow", group: "Accueil - sections", label: "Témoignages : petit titre", type: "text", fields: null, value: "Avis clients" },
  { key: "home.testimonials_title", group: "Accueil - sections", label: "Témoignages : titre", type: "text", fields: null, value: "Nos clients parlent de nous" },
  { key: "pages.service_presentation", group: "Pages de détail et listes", label: "Fiche service : titre présentation", type: "text", fields: null, value: "Présentation" },
  { key: "pages.service_prestations", group: "Pages de détail et listes", label: "Fiche service : titre prestations", type: "text", fields: null, value: "Nos prestations" },
  { key: "pages.service_related_eyebrow", group: "Pages de détail et listes", label: "Fiche service : petit titre réalisations", type: "text", fields: null, value: "Portfolio" },
  { key: "pages.service_related_title", group: "Pages de détail et listes", label: "Fiche service : titre réalisations liées", type: "text", fields: null, value: "Réalisations liées" },
  { key: "pages.quote_button", group: "Pages de détail et listes", label: "Bouton « Demander un devis » (fiches)", type: "text", fields: null, value: "Demander un devis" },
  { key: "pages.products_eyebrow", group: "Pages de détail et listes", label: "Fiche produit : petit titre", type: "text", fields: null, value: "Catalogue" },
  { key: "pages.products_similar_title", group: "Pages de détail et listes", label: "Fiche produit : titre similaires", type: "text", fields: null, value: "Produits similaires" },
  { key: "pages.projects_similar_title", group: "Pages de détail et listes", label: "Fiche réalisation : titre similaires", type: "text", fields: null, value: "Réalisations similaires" },
  { key: "pages.articles_eyebrow", group: "Pages de détail et listes", label: "Fiche actualité : petit titre", type: "text", fields: null, value: "À lire aussi" },
  { key: "pages.articles_similar_title", group: "Pages de détail et listes", label: "Fiche actualité : titre autres", type: "text", fields: null, value: "Autres actualités" },
  { key: "pages.quote_side_title", group: "Pages de détail et listes", label: "Page devis : titre latéral", type: "text", fields: null, value: "Besoin d'échanger directement ?" },
  { key: "pages.quote_side_text", group: "Pages de détail et listes", label: "Page devis : texte latéral", type: "textarea", fields: null, value: "Notre équipe reste disponible par téléphone ou WhatsApp pour répondre à vos questions." },
  { key: "about.hero_eyebrow", group: "À propos", label: "Bannière : petit titre", type: "text", fields: null, value: "ENGOBO GROUP" },
  { key: "about.hero_title", group: "À propos", label: "Bannière : titre", type: "text", fields: null, value: "À propos de nous" },
  { key: "about.hero_description", group: "À propos", label: "Bannière : texte", type: "textarea", fields: null, value: "Une entreprise multi-services au service de vos projets, de l'importation à la pose finale." },
  { key: "about.history_title", group: "À propos", label: "Notre histoire : titre", type: "text", fields: null, value: "Notre histoire" },
  { key: "about.history_text", group: "À propos", label: "Notre histoire : premier paragraphe", type: "textarea", fields: null, value: "Née de la volonté de proposer une offre complète à nos clients, ENGOBO GROUP a réuni sous une même bannière l'importation, la marbrerie, l'ébénisterie, la menuiserie et le commerce général." },
  { key: "about.history_extra", group: "À propos", label: "Notre histoire : second paragraphe", type: "textarea", fields: null, value: "Cette organisation nous permet de piloter chaque projet de bout en bout, avec un interlocuteur unique et une qualité constante." },
  { key: "about.stats", group: "À propos", label: "Chiffres clés (un par ligne : valeur | libellé)", type: "pairs", fields: ["value","label"], value: "40+ | Réalisations livrées\n100% | Projets sur mesure" },
  { key: "about.mission_title", group: "À propos", label: "Mission : titre", type: "text", fields: null, value: "Notre mission" },
  { key: "about.mission_text", group: "À propos", label: "Mission : texte", type: "textarea", fields: null, value: "Accompagner particuliers et professionnels dans la réalisation de leurs projets, en alliant matériaux de qualité, savoir-faire artisanal et accompagnement personnalisé, du devis à la pose." },
  { key: "about.vision_title", group: "À propos", label: "Vision : titre", type: "text", fields: null, value: "Notre vision" },
  { key: "about.vision_text", group: "À propos", label: "Vision : texte", type: "textarea", fields: null, value: "Devenir la référence multi-services en marbrerie, menuiserie et ébénisterie à Pointe-Noire, reconnue pour l'exigence de ses réalisations et la satisfaction durable de ses clients." },
  { key: "about.savoir_faire_title", group: "À propos", label: "Savoir-faire : titre", type: "text", fields: null, value: "Notre savoir-faire" },
  { key: "about.savoir_faire_text", group: "À propos", label: "Savoir-faire : texte", type: "textarea", fields: null, value: "Des équipes formées aux techniques traditionnelles et modernes, du choix de la matière à la pose finale." },
  { key: "about.values", group: "À propos", label: "Nos valeurs (une par ligne : titre | description)", type: "pairs", fields: ["title","description"], value: "Qualité | Des matériaux sélectionnés et des finitions soignées à chaque étape.\nEngagement | Le respect des délais et des engagements pris envers nos clients.\nSavoir-faire | Des équipes formées aux techniques traditionnelles et modernes.\nConfiance | Un accompagnement transparent, du devis à la livraison." },
  { key: "about.team_eyebrow", group: "À propos", label: "Équipe : petit titre", type: "text", fields: null, value: "Notre équipe" },
  { key: "about.team_title", group: "À propos", label: "Équipe : titre", type: "text", fields: null, value: "Des artisans passionnés" },
  { key: "about.team_description", group: "À propos", label: "Équipe : texte", type: "textarea", fields: null, value: "Des ébénistes, marbriers et menuisiers expérimentés, réunis autour d'un même souci de la qualité." },
];
